-- Address records (must be inserted first — agreements now has a foreign key to this table)
INSERT INTO address (id, street_name, city, country) VALUES (1, '123 Maple St', 'Springfield', 'USA');
INSERT INTO address (id, street_name, city, country) VALUES (2, '456 Oak Ave', 'Austin', 'USA');
INSERT INTO address (id, street_name, city, country) VALUES (3, '789 Pine Rd', 'Denver', 'USA');
INSERT INTO address (id, street_name, city, country) VALUES (4, '321 Cedar Blvd', 'Seattle', 'USA');
INSERT INTO address (id, street_name, city, country) VALUES (5, '654 Birch Ln', 'Portland', 'USA');
INSERT INTO address (id, street_name, city, country) VALUES (6, '987 Elm St', 'Chicago', 'USA');
INSERT INTO address (id, street_name, city, country) VALUES (7, '246 Walnut Dr', 'Miami', 'USA');
INSERT INTO address (id, street_name, city, country) VALUES (8, '135 Spruce Ct', 'Boston', 'USA');
INSERT INTO address (id, street_name, city, country) VALUES (9, '864 Ash Way', 'Phoenix', 'USA');
INSERT INTO address (id, street_name, city, country) VALUES (10, '753 Willow Pl', 'San Diego', 'USA');
INSERT INTO address (id, street_name, city, country) VALUES (11, '159 Chestnut Ave', 'Atlanta', 'USA');
INSERT INTO address (id, street_name, city, country) VALUES (12, '357 Poplar St', 'Nashville', 'USA');
INSERT INTO address (id, street_name, city, country) VALUES (13, '951 Sycamore Rd', 'Dallas', 'USA');
INSERT INTO address (id, street_name, city, country) VALUES (14, '258 Magnolia Dr', 'Orlando', 'USA');
INSERT INTO address (id, street_name, city, country) VALUES (15, '369 Dogwood Ln', 'Charlotte', 'USA');
INSERT INTO address (id, street_name, city, country) VALUES (16, '741 Redwood Ct', 'Sacramento', 'USA');
INSERT INTO address (id, street_name, city, country) VALUES (17, '852 Fir St', 'Minneapolis', 'USA');
INSERT INTO address (id, street_name, city, country) VALUES (18, '963 Hickory Ave', 'Columbus', 'USA');
INSERT INTO address (id, street_name, city, country) VALUES (19, '147 Juniper Blvd', 'Raleigh', 'USA');
INSERT INTO address (id, street_name, city, country) VALUES (20, '258 Laurel Dr', 'Las Vegas', 'USA');

-- Agreement records (one-to-one to address here, since no address is reused; each agreement points to its own address_id)
INSERT INTO agreements (id, owner_id, policy_number, address_id) VALUES (1, 1, 'POL-100001', 1);
INSERT INTO agreements (id, owner_id, policy_number, address_id) VALUES (2, 2, 'POL-100002', 2);
INSERT INTO agreements (id, owner_id, policy_number, address_id) VALUES (3, 3, 'POL-100003', 3);
INSERT INTO agreements (id, owner_id, policy_number, address_id) VALUES (4, 4, 'POL-100004', 4);
INSERT INTO agreements (id, owner_id, policy_number, address_id) VALUES (5, 5, 'POL-100005', 5);
INSERT INTO agreements (id, owner_id, policy_number, address_id) VALUES (6, 6, 'POL-100006', 6);
INSERT INTO agreements (id, owner_id, policy_number, address_id) VALUES (7, 7, 'POL-100007', 7);
INSERT INTO agreements (id, owner_id, policy_number, address_id) VALUES (8, 8, 'POL-100008', 8);
INSERT INTO agreements (id, owner_id, policy_number, address_id) VALUES (9, 9, 'POL-100009', 9);
INSERT INTO agreements (id, owner_id, policy_number, address_id) VALUES (10, 10, 'POL-100010', 10);
INSERT INTO agreements (id, owner_id, policy_number, address_id) VALUES (11, 11, 'POL-100011', 11);
INSERT INTO agreements (id, owner_id, policy_number, address_id) VALUES (12, 3, 'POL-100012', 12);
INSERT INTO agreements (id, owner_id, policy_number, address_id) VALUES (13, 13, 'POL-100013', 13);
INSERT INTO agreements (id, owner_id, policy_number, address_id) VALUES (14, 14, 'POL-100014', 14);
INSERT INTO agreements (id, owner_id, policy_number, address_id) VALUES (15, 15, 'POL-100015', 15);
INSERT INTO agreements (id, owner_id, policy_number, address_id) VALUES (16, 16, 'POL-100016', 16);
INSERT INTO agreements (id, owner_id, policy_number, address_id) VALUES (17, 17, 'POL-100017', 17);
INSERT INTO agreements (id, owner_id, policy_number, address_id) VALUES (18, 3, 'POL-100018', 18);
INSERT INTO agreements (id, owner_id, policy_number, address_id) VALUES (19, 19, 'POL-100019', 19);
INSERT INTO agreements (id, owner_id, policy_number, address_id) VALUES (20, 20, 'POL-100020', 20);